CREATE OR REPLACE 
PACKAGE PKG_PRODUCTO AS 

  PROCEDURE SP_LISTAR(
     P_CURSOR  OUT SYS_REFCURSOR
  );

 PROCEDURE SP_LISTAR_X_NOMBRE(
     P_CURSOR  OUT SYS_REFCURSOR,
     P_NOMBRE  IN PRODUCTO.NOMBRE%TYPE
  );
  
END PKG_PRODUCTO;
CREATE OR REPLACE
PACKAGE BODY PKG_PRODUCTO AS 

  PROCEDURE SP_LISTAR(
     P_CURSOR  OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN 
        P_CURSOR
    FOR
        SELECT
            ID,
            NOMBRE,
            PRECIO,
            STOCK
        FROM
            PRODUCTO;
        
  END SP_LISTAR;

 PROCEDURE SP_LISTAR_X_NOMBRE(
     P_CURSOR  OUT SYS_REFCURSOR,
     P_NOMBRE  IN PRODUCTO.NOMBRE%TYPE
  )AS
  BEGIN
   OPEN 
        P_CURSOR
    FOR
        SELECT
            ID,
            NOMBRE,
            PRECIO,
            STOCK
        FROM
            PRODUCTO
        WHERE
            UPPER(NOMBRE) LIKE '%'||UPPER(P_NOMBRE)||'%';

  END SP_LISTAR_X_NOMBRE;
END PKG_PRODUCTO;
